/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Color { 'b' : number, 'g' : number, 'r' : number }
export interface GeneratedLogoProjectSerialized {
  'description' : string,
  'timestamp' : bigint,
  'logoSpecification' : LogoSpecification,
}
export interface LogoSpecification {
  'shapes' : Array<Shape>,
  'style' : string,
  'colors' : Array<Color>,
}
export type Shape = { 'circle' : bigint } |
  { 'square' : bigint } |
  { 'triangle' : bigint };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToFavorites' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cloneProject' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'editProject' : ActorMethod<[string, string, LogoSpecification], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<GeneratedLogoProjectSerialized>>,
  'getSortedLogoProjects' : ActorMethod<
    [],
    Array<GeneratedLogoProjectSerialized>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getViewedProjects' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsViewed' : ActorMethod<[string], undefined>,
  'removeFromFavorites' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGeneratedLogoProject' : ActorMethod<
    [string, LogoSpecification],
    undefined
  >,
  'searchProjectsByDescription' : ActorMethod<
    [string],
    Array<GeneratedLogoProjectSerialized>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];