/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Shape = IDL.Variant({
  'circle' : IDL.Nat,
  'square' : IDL.Nat,
  'triangle' : IDL.Nat,
});
export const Color = IDL.Record({
  'b' : IDL.Nat8,
  'g' : IDL.Nat8,
  'r' : IDL.Nat8,
});
export const LogoSpecification = IDL.Record({
  'shapes' : IDL.Vec(Shape),
  'style' : IDL.Text,
  'colors' : IDL.Vec(Color),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GeneratedLogoProjectSerialized = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'logoSpecification' : LogoSpecification,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToFavorites' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cloneProject' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'editProject' : IDL.Func([IDL.Text, IDL.Text, LogoSpecification], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func(
      [],
      [IDL.Vec(GeneratedLogoProjectSerialized)],
      ['query'],
    ),
  'getSortedLogoProjects' : IDL.Func(
      [],
      [IDL.Vec(GeneratedLogoProjectSerialized)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getViewedProjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsViewed' : IDL.Func([IDL.Text], [], []),
  'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGeneratedLogoProject' : IDL.Func([IDL.Text, LogoSpecification], [], []),
  'searchProjectsByDescription' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GeneratedLogoProjectSerialized)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Shape = IDL.Variant({
    'circle' : IDL.Nat,
    'square' : IDL.Nat,
    'triangle' : IDL.Nat,
  });
  const Color = IDL.Record({ 'b' : IDL.Nat8, 'g' : IDL.Nat8, 'r' : IDL.Nat8 });
  const LogoSpecification = IDL.Record({
    'shapes' : IDL.Vec(Shape),
    'style' : IDL.Text,
    'colors' : IDL.Vec(Color),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GeneratedLogoProjectSerialized = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'logoSpecification' : LogoSpecification,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToFavorites' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cloneProject' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'editProject' : IDL.Func([IDL.Text, IDL.Text, LogoSpecification], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func(
        [],
        [IDL.Vec(GeneratedLogoProjectSerialized)],
        ['query'],
      ),
    'getSortedLogoProjects' : IDL.Func(
        [],
        [IDL.Vec(GeneratedLogoProjectSerialized)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getViewedProjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsViewed' : IDL.Func([IDL.Text], [], []),
    'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGeneratedLogoProject' : IDL.Func(
        [IDL.Text, LogoSpecification],
        [],
        [],
      ),
    'searchProjectsByDescription' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GeneratedLogoProjectSerialized)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };