/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Color {
    b: number;
    g: number;
    r: number;
}
export interface GeneratedLogoProjectSerialized {
    description: string;
    timestamp: bigint;
    logoSpecification: LogoSpecification;
}
export type Shape = {
    __kind__: "circle";
    circle: bigint;
} | {
    __kind__: "square";
    square: bigint;
} | {
    __kind__: "triangle";
    triangle: bigint;
};
export interface UserProfile {
    name: string;
}
export interface LogoSpecification {
    shapes: Array<Shape>;
    style: string;
    colors: Array<Color>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToFavorites(projectId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cloneProject(projectId: string): Promise<void>;
    deleteProject(projectId: string): Promise<void>;
    editProject(projectId: string, newDescription: string, newLogoSpec: LogoSpecification): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(): Promise<Array<GeneratedLogoProjectSerialized>>;
    getSortedLogoProjects(): Promise<Array<GeneratedLogoProjectSerialized>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getViewedProjects(): Promise<Array<string>>;
    isCallerAdmin(): Promise<boolean>;
    markAsViewed(projectId: string): Promise<void>;
    removeFromFavorites(projectId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveGeneratedLogoProject(description: string, logoSpec: LogoSpecification): Promise<void>;
    searchProjectsByDescription(searchTerm: string): Promise<Array<GeneratedLogoProjectSerialized>>;
}
import type { Color as _Color, GeneratedLogoProjectSerialized as _GeneratedLogoProjectSerialized, LogoSpecification as _LogoSpecification, Shape as _Shape, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToFavorites(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToFavorites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToFavorites(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cloneProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cloneProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cloneProject(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async editProject(arg0: string, arg1: string, arg2: LogoSpecification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProject(arg0, arg1, to_candid_LogoSpecification_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProject(arg0, arg1, to_candid_LogoSpecification_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<GeneratedLogoProjectSerialized>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedLogoProjects(): Promise<Array<GeneratedLogoProjectSerialized>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedLogoProjects();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedLogoProjects();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getViewedProjects(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewedProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewedProjects();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAsViewed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsViewed(arg0);
            return result;
        }
    }
    async removeFromFavorites(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromFavorites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromFavorites(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveGeneratedLogoProject(arg0: string, arg1: LogoSpecification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGeneratedLogoProject(arg0, to_candid_LogoSpecification_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGeneratedLogoProject(arg0, to_candid_LogoSpecification_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async searchProjectsByDescription(arg0: string): Promise<Array<GeneratedLogoProjectSerialized>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProjectsByDescription(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProjectsByDescription(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_GeneratedLogoProjectSerialized_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratedLogoProjectSerialized): GeneratedLogoProjectSerialized {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LogoSpecification_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogoSpecification): LogoSpecification {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Shape_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shape): Shape {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    timestamp: bigint;
    logoSpecification: _LogoSpecification;
}): {
    description: string;
    timestamp: bigint;
    logoSpecification: LogoSpecification;
} {
    return {
        description: value.description,
        timestamp: value.timestamp,
        logoSpecification: from_candid_LogoSpecification_n14(_uploadFile, _downloadFile, value.logoSpecification)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shapes: Array<_Shape>;
    style: string;
    colors: Array<_Color>;
}): {
    shapes: Array<Shape>;
    style: string;
    colors: Array<Color>;
} {
    return {
        shapes: from_candid_vec_n16(_uploadFile, _downloadFile, value.shapes),
        style: value.style,
        colors: value.colors
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    circle: bigint;
} | {
    square: bigint;
} | {
    triangle: bigint;
}): {
    __kind__: "circle";
    circle: bigint;
} | {
    __kind__: "square";
    square: bigint;
} | {
    __kind__: "triangle";
    triangle: bigint;
} {
    return "circle" in value ? {
        __kind__: "circle",
        circle: value.circle
    } : "square" in value ? {
        __kind__: "square",
        square: value.square
    } : "triangle" in value ? {
        __kind__: "triangle",
        triangle: value.triangle
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GeneratedLogoProjectSerialized>): Array<GeneratedLogoProjectSerialized> {
    return value.map((x)=>from_candid_GeneratedLogoProjectSerialized_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shape>): Array<Shape> {
    return value.map((x)=>from_candid_Shape_n17(_uploadFile, _downloadFile, x));
}
function to_candid_LogoSpecification_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogoSpecification): _LogoSpecification {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Shape_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shape): _Shape {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shapes: Array<Shape>;
    style: string;
    colors: Array<Color>;
}): {
    shapes: Array<_Shape>;
    style: string;
    colors: Array<_Color>;
} {
    return {
        shapes: to_candid_vec_n5(_uploadFile, _downloadFile, value.shapes),
        style: value.style,
        colors: value.colors
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "circle";
    circle: bigint;
} | {
    __kind__: "square";
    square: bigint;
} | {
    __kind__: "triangle";
    triangle: bigint;
}): {
    circle: bigint;
} | {
    square: bigint;
} | {
    triangle: bigint;
} {
    return value.__kind__ === "circle" ? {
        circle: value.circle
    } : value.__kind__ === "square" ? {
        square: value.square
    } : value.__kind__ === "triangle" ? {
        triangle: value.triangle
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Shape>): Array<_Shape> {
    return value.map((x)=>to_candid_Shape_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
